function highlightmovie(cn,multions)
% cn is a countour file generated by "findcells" or "labelcells".  This
% will plot and label the contours specified in that cell array.  Labels
% will correspond with cell numbers in matrices generated from in other
% m-files (except in cases where activeon or activevalues are used, because
% those variables have inactive cells deleted from them).

% this function is different from "plotfromcontours" in that it uses the
% "ons" to highlight specific cells (contours).  "ons" should correspond to
% the cells which are on in just one frame.  

%this is different from highlightons because it will desplay the ons for
%multiple frames, depending on the input

for w=1:size(multions,1);
    ons=multions(w,:);
    figure('units','normalized','position',[.25 .25 .25 .25]);
    for t=1:length(cn);
%         xlim([0 255]);
%         ylim([0 255]);
        set(gca,'YDir','reverse');
        hold on;
        plot(cn{t}(:,1), cn{t}(:,2),'color',[.5,.5,.5]);
	end
	
	n=find(ons);
    %not is if you need to exclude some cells... ie you ablated them.
%     not = [24    73    84    89   104   122    13    18    29    79    80   130   167];
    not = [];
    n = setdiff(n,not);
	for u=1:length(n);
%         patch(cn{n(u)}(:,1),cn{n(u)}(:,2),[.65 0 .65],'edgecolor',[.65 0 .65]);%purple
        patch(cn{n(u)}(:,1),cn{n(u)}(:,2),'k','edgecolor','k');
%         patch(cn{n(u)}(:,1),cn{n(u)}(:,2),[.4 .4 1],'edgecolor',[.4 .4 1]);
%         patch(cn{n(u)}(:,1),cn{n(u)}(:,2),[.5,1,.5],'edgecolor',[.3,1,.3]);
	end
axis equal
axis off
% plot([0 255 255 0 0],[0 0 255 255 0],'k')
%     m(w)=getframe;
%     name=num2str(w);
%     name=strcat('frame',name);
%     print ('-dmeta', name)
end
% whos
% movie(m)

