function [cluster,xcluster,ycluster,percentile]=evalclustering(ons,conts);

% function [cluster,xcluster,ycluster,over5]=evalclustering(ons,conts);

%ons is a 1D vector of ons corresponding to a whether or not each contour
%was on in a single frame.  Conts are the contour traces for each cell.
%Output variables will be 1 or 0: 1 if the ons are clustered in that
%dimension 0 if not.
%percentile is a value between .1 and 100 which represents where the
%particular set of cells on in question lie in relation to the set of
%clusters generated by random shuffling.

cluster=0;
xcluster=0;
ycluster=0;
over5=0;
if sum(ons)>=5;%only evaluate if there are 5 or more cells on
    over5=1;
	[avgdist,avgdistx,avgdisty]=spatialclustering(ons,conts);
	
	for a=1:1000;
        shuffons{a}=reshufflewhichcells(ons);
%         if a<20;
%             figure;
%             highlightons(conts,shuffons);
%         end
        [shuffdist(a),shuffxdist(a),shuffydist(a)]=spatialclustering(shuffons,conts);
	end
	
	shuffdist=sort(shuffdist);
	shuffxdist=sort(shuffxdist);
	shuffydist=sort(shuffydist);
	
	thresh=shuffdist(50);
	xthresh=shuffxdist(50);
	ythresh=shuffydist(50);
	
	if avgdist<=thresh;
%         disp('These cells are significantly clustered');
        cluster=1;
	end
	
	if avgdistx<=xthresh;
%         disp('These cells are significantly clustered in x: ie they form a column');
        xcluster=1;
	end
	
	if avgdisty<=ythresh;
%         disp('These cells are significantly clustered in y: ie they form a row (layer)');
        ycluster=1;
	end
    
    percentile=size(find(shuffdist>avgdist),2);%gives the lower of the sorted reshuffled distances the avgdist would fall between
    percentile=percentile/10;%gives the percentile rank of the group in question within the randomly generated groups: how clustered is it: 99%ile is more clustered than 1% here
    if percentile<.1;
        percentile=.1;
    end
end