function plotfromcontours(cn)
% cn is a countour file generated by "findcells" or "labelcells".  This
% will plot and label the contours specified in that cell array.  Labels
% will correspond with cell numbers in matrices generated from in other
% m-files (except in cases where activeon or activevalues are used, because
% those variables have inactive cells deleted from them).
% figure
for t=1:length(cn);
%     xlim([0 255]);
%     ylim([0 255]);
    set(gca,'YDir','reverse');
    hold on;
    plot(cn{t}(:,1), cn{t}(:,2),'k');
%     label=num2str(t);
%     text(cn{t}(1,1),cn{t}(1,2),label);
end
axis equal
axis off
% plot([0 255 255 0 0],[0 0 255 255 0],'k')